version: '3.8'

services:
  backend:
    build: ./services/backend
    container_name: fastapi_web_container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/supernote  # Adjust the database name as needed
      - S3_ACCESS=M0Px6rRl2pw5Yxese1vG
      - S3_SECRET=tmsAHAHS41qqQ5Rr5EIKmS7inJGvX8s5kiRk9NXF
      - S3_URI=http://minio:9000
      - S3_BUCKET=super-note-bucket
      - JWT_SECRET=Super#Secret@JWT&123
    depends_on:
      - mongo
      - minio
  
  frontend:
    build: ./services/frontend
    container_name: react_web_container
    ports:
      - "8080:8080"
    environment:
      - SERVER=http://localhost:8000/
    volumes:
      - ./services/frontend:/usr/src/app
  
  # signal:
  #   build: ./services/signal
  #   container_name: signal_ws_container
  #   ports:
  #     - "4444:4444"
  #   volumes:
  #     - ./services/signal:/usr/src/app

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
  
  minio:
    image: minio/minio:latest
    container_name: minio_container
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root@root
      MINIO_SERVER_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  minio-data:
  mongodb_data: