FROM python:3.9-slim

# Create and set working directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "/usr/src/app"

# install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libev-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install pipenv and compile dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/

# Specify the command to run on container start
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]